# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanner.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(417, 544)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_17 = QtWidgets.QLabel(Dialog)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 18, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 19, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.label_28, 13, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 9, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 12, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 17, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 20, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 21, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 22, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 8, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 14, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 16, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 23, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setObjectName("label_27")
        self.gridLayout_4.addWidget(self.label_27, 11, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 15, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 26, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 25, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 24, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setObjectName("label_22")
        self.gridLayout_4.addWidget(self.label_22, 27, 0, 1, 1)
        self.AUDCAD_PRICE = QtWidgets.QLabel(Dialog)
        self.AUDCAD_PRICE.setObjectName("AUDCAD_PRICE")
        self.gridLayout_4.addWidget(self.AUDCAD_PRICE, 0, 1, 1, 1)
        self.AUDCHF_PRICE = QtWidgets.QLabel(Dialog)
        self.AUDCHF_PRICE.setObjectName("AUDCHF_PRICE")
        self.gridLayout_4.addWidget(self.AUDCHF_PRICE, 1, 1, 1, 1)
        self.AUDJPY_PRICE = QtWidgets.QLabel(Dialog)
        self.AUDJPY_PRICE.setObjectName("AUDJPY_PRICE")
        self.gridLayout_4.addWidget(self.AUDJPY_PRICE, 2, 1, 1, 1)
        self.AUDNZD_PRICE = QtWidgets.QLabel(Dialog)
        self.AUDNZD_PRICE.setObjectName("AUDNZD_PRICE")
        self.gridLayout_4.addWidget(self.AUDNZD_PRICE, 3, 1, 1, 1)
        self.AUDUSD_PRICE = QtWidgets.QLabel(Dialog)
        self.AUDUSD_PRICE.setObjectName("AUDUSD_PRICE")
        self.gridLayout_4.addWidget(self.AUDUSD_PRICE, 4, 1, 1, 1)
        self.CADCHF_PRICE = QtWidgets.QLabel(Dialog)
        self.CADCHF_PRICE.setObjectName("CADCHF_PRICE")
        self.gridLayout_4.addWidget(self.CADCHF_PRICE, 5, 1, 1, 1)
        self.CADJPY_PRICE = QtWidgets.QLabel(Dialog)
        self.CADJPY_PRICE.setObjectName("CADJPY_PRICE")
        self.gridLayout_4.addWidget(self.CADJPY_PRICE, 6, 1, 1, 1)
        self.CHFJPY_PRICE = QtWidgets.QLabel(Dialog)
        self.CHFJPY_PRICE.setObjectName("CHFJPY_PRICE")
        self.gridLayout_4.addWidget(self.CHFJPY_PRICE, 7, 1, 1, 1)
        self.EURAUD_PRICE = QtWidgets.QLabel(Dialog)
        self.EURAUD_PRICE.setObjectName("EURAUD_PRICE")
        self.gridLayout_4.addWidget(self.EURAUD_PRICE, 8, 1, 1, 1)
        self.EURCAD_PRICE = QtWidgets.QLabel(Dialog)
        self.EURCAD_PRICE.setObjectName("EURCAD_PRICE")
        self.gridLayout_4.addWidget(self.EURCAD_PRICE, 9, 1, 1, 1)
        self.EURCHF_PRICE = QtWidgets.QLabel(Dialog)
        self.EURCHF_PRICE.setObjectName("EURCHF_PRICE")
        self.gridLayout_4.addWidget(self.EURCHF_PRICE, 10, 1, 1, 1)
        self.EURGBP_PRICE = QtWidgets.QLabel(Dialog)
        self.EURGBP_PRICE.setObjectName("EURGBP_PRICE")
        self.gridLayout_4.addWidget(self.EURGBP_PRICE, 11, 1, 1, 1)
        self.EURJPY_PRICE = QtWidgets.QLabel(Dialog)
        self.EURJPY_PRICE.setObjectName("EURJPY_PRICE")
        self.gridLayout_4.addWidget(self.EURJPY_PRICE, 12, 1, 1, 1)
        self.EURNZD_PRICE = QtWidgets.QLabel(Dialog)
        self.EURNZD_PRICE.setObjectName("EURNZD_PRICE")
        self.gridLayout_4.addWidget(self.EURNZD_PRICE, 13, 1, 1, 1)
        self.EURUSD_PRICE = QtWidgets.QLabel(Dialog)
        self.EURUSD_PRICE.setObjectName("EURUSD_PRICE")
        self.gridLayout_4.addWidget(self.EURUSD_PRICE, 14, 1, 1, 1)
        self.GBPAUD_PRICE = QtWidgets.QLabel(Dialog)
        self.GBPAUD_PRICE.setObjectName("GBPAUD_PRICE")
        self.gridLayout_4.addWidget(self.GBPAUD_PRICE, 15, 1, 1, 1)
        self.GBPCAD_PRICE = QtWidgets.QLabel(Dialog)
        self.GBPCAD_PRICE.setObjectName("GBPCAD_PRICE")
        self.gridLayout_4.addWidget(self.GBPCAD_PRICE, 16, 1, 1, 1)
        self.GBPCHF_PRICE = QtWidgets.QLabel(Dialog)
        self.GBPCHF_PRICE.setObjectName("GBPCHF_PRICE")
        self.gridLayout_4.addWidget(self.GBPCHF_PRICE, 17, 1, 1, 1)
        self.GBPJPY_PRICE = QtWidgets.QLabel(Dialog)
        self.GBPJPY_PRICE.setObjectName("GBPJPY_PRICE")
        self.gridLayout_4.addWidget(self.GBPJPY_PRICE, 18, 1, 1, 1)
        self.GBPNZD_PRICE = QtWidgets.QLabel(Dialog)
        self.GBPNZD_PRICE.setObjectName("GBPNZD_PRICE")
        self.gridLayout_4.addWidget(self.GBPNZD_PRICE, 19, 1, 1, 1)
        self.GBPUSD_PRICE = QtWidgets.QLabel(Dialog)
        self.GBPUSD_PRICE.setObjectName("GBPUSD_PRICE")
        self.gridLayout_4.addWidget(self.GBPUSD_PRICE, 20, 1, 1, 1)
        self.NZDCAD_PRICE = QtWidgets.QLabel(Dialog)
        self.NZDCAD_PRICE.setObjectName("NZDCAD_PRICE")
        self.gridLayout_4.addWidget(self.NZDCAD_PRICE, 21, 1, 1, 1)
        self.NZDCHF_PRICE = QtWidgets.QLabel(Dialog)
        self.NZDCHF_PRICE.setObjectName("NZDCHF_PRICE")
        self.gridLayout_4.addWidget(self.NZDCHF_PRICE, 22, 1, 1, 1)
        self.NZDJPY_PRICE = QtWidgets.QLabel(Dialog)
        self.NZDJPY_PRICE.setObjectName("NZDJPY_PRICE")
        self.gridLayout_4.addWidget(self.NZDJPY_PRICE, 23, 1, 1, 1)
        self.NZDUSD_PRICE = QtWidgets.QLabel(Dialog)
        self.NZDUSD_PRICE.setObjectName("NZDUSD_PRICE")
        self.gridLayout_4.addWidget(self.NZDUSD_PRICE, 24, 1, 1, 1)
        self.USDCAD_PRICE = QtWidgets.QLabel(Dialog)
        self.USDCAD_PRICE.setObjectName("USDCAD_PRICE")
        self.gridLayout_4.addWidget(self.USDCAD_PRICE, 25, 1, 1, 1)
        self.USDCHF_PRICE = QtWidgets.QLabel(Dialog)
        self.USDCHF_PRICE.setObjectName("USDCHF_PRICE")
        self.gridLayout_4.addWidget(self.USDCHF_PRICE, 26, 1, 1, 1)
        self.USDJPY_PRICE = QtWidgets.QLabel(Dialog)
        self.USDJPY_PRICE.setObjectName("USDJPY_PRICE")
        self.gridLayout_4.addWidget(self.USDJPY_PRICE, 27, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_17.setText(_translate("Dialog", "GBPJPY"))
        self.label_18.setText(_translate("Dialog", "GBPNZD"))
        self.label_28.setText(_translate("Dialog", "EURNZD"))
        self.label_6.setText(_translate("Dialog", "AUDUSD"))
        self.label_5.setText(_translate("Dialog", "EURCAD"))
        self.label_8.setText(_translate("Dialog", "CADJPY"))
        self.label_11.setText(_translate("Dialog", "EURCHF"))
        self.label_3.setText(_translate("Dialog", "AUDJPY"))
        self.label_7.setText(_translate("Dialog", "AUDNZD"))
        self.label_4.setText(_translate("Dialog", "CADCHF"))
        self.label_9.setText(_translate("Dialog", "CHFJPY"))
        self.label_12.setText(_translate("Dialog", "EURJPY"))
        self.label_16.setText(_translate("Dialog", "GBPCHF"))
        self.label_19.setText(_translate("Dialog", "GBPUSD"))
        self.label_20.setText(_translate("Dialog", "NZDCAD"))
        self.label_21.setText(_translate("Dialog", "NZDCHF"))
        self.label.setText(_translate("Dialog", "AUDCAD"))
        self.label_10.setText(_translate("Dialog", "EURAUD"))
        self.label_13.setText(_translate("Dialog", "EURUSD"))
        self.label_15.setText(_translate("Dialog", "GBPCAD"))
        self.label_26.setText(_translate("Dialog", "NZDJPY"))
        self.label_2.setText(_translate("Dialog", "AUDCHF"))
        self.label_27.setText(_translate("Dialog", "EURGBP"))
        self.label_14.setText(_translate("Dialog", "GBPAUD"))
        self.label_23.setText(_translate("Dialog", "USDCHF"))
        self.label_24.setText(_translate("Dialog", "USDCAD"))
        self.label_25.setText(_translate("Dialog", "NZDUSD"))
        self.label_22.setText(_translate("Dialog", "USDJPY"))
        self.AUDCAD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.AUDCHF_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.AUDJPY_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.AUDNZD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.AUDUSD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.CADCHF_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.CADJPY_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.CHFJPY_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.EURAUD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.EURCAD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.EURCHF_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.EURGBP_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.EURJPY_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.EURNZD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.EURUSD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.GBPAUD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.GBPCAD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.GBPCHF_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.GBPJPY_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.GBPNZD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.GBPUSD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.NZDCAD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.NZDCHF_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.NZDJPY_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.NZDUSD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.USDCAD_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.USDCHF_PRICE.setText(_translate("Dialog", "TextLabel"))
        self.USDJPY_PRICE.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

