# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanner.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(417, 544)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.LABEL_AUDCAD = QtWidgets.QLabel(Dialog)
        self.LABEL_AUDCAD.setObjectName("LABEL_AUDCAD")
        self.gridLayout_4.addWidget(self.LABEL_AUDCAD, 1, 0, 1, 1)
        self.LABEL_AUDUSD = QtWidgets.QLabel(Dialog)
        self.LABEL_AUDUSD.setObjectName("LABEL_AUDUSD")
        self.gridLayout_4.addWidget(self.LABEL_AUDUSD, 5, 0, 1, 1)
        self.LABEL_EURNZD = QtWidgets.QLabel(Dialog)
        self.LABEL_EURNZD.setObjectName("LABEL_EURNZD")
        self.gridLayout_4.addWidget(self.LABEL_EURNZD, 14, 0, 1, 1)
        self.LABEL_GBPJPY = QtWidgets.QLabel(Dialog)
        self.LABEL_GBPJPY.setObjectName("LABEL_GBPJPY")
        self.gridLayout_4.addWidget(self.LABEL_GBPJPY, 19, 0, 1, 1)
        self.LABEL_GBPNZD = QtWidgets.QLabel(Dialog)
        self.LABEL_GBPNZD.setObjectName("LABEL_GBPNZD")
        self.gridLayout_4.addWidget(self.LABEL_GBPNZD, 20, 0, 1, 1)
        self.LABEL_CADJPY = QtWidgets.QLabel(Dialog)
        self.LABEL_CADJPY.setObjectName("LABEL_CADJPY")
        self.gridLayout_4.addWidget(self.LABEL_CADJPY, 7, 0, 1, 1)
        self.LABEL_EURCHF = QtWidgets.QLabel(Dialog)
        self.LABEL_EURCHF.setObjectName("LABEL_EURCHF")
        self.gridLayout_4.addWidget(self.LABEL_EURCHF, 11, 0, 1, 1)
        self.LABEL_AUDJPY = QtWidgets.QLabel(Dialog)
        self.LABEL_AUDJPY.setObjectName("LABEL_AUDJPY")
        self.gridLayout_4.addWidget(self.LABEL_AUDJPY, 3, 0, 1, 1)
        self.LABEL_EURCAD = QtWidgets.QLabel(Dialog)
        self.LABEL_EURCAD.setObjectName("LABEL_EURCAD")
        self.gridLayout_4.addWidget(self.LABEL_EURCAD, 10, 0, 1, 1)
        self.LABEL_AUDNZD = QtWidgets.QLabel(Dialog)
        self.LABEL_AUDNZD.setObjectName("LABEL_AUDNZD")
        self.gridLayout_4.addWidget(self.LABEL_AUDNZD, 4, 0, 1, 1)
        self.LABEL_GBPCHF = QtWidgets.QLabel(Dialog)
        self.LABEL_GBPCHF.setObjectName("LABEL_GBPCHF")
        self.gridLayout_4.addWidget(self.LABEL_GBPCHF, 18, 0, 1, 1)
        self.LABEL_CHFJPY = QtWidgets.QLabel(Dialog)
        self.LABEL_CHFJPY.setObjectName("LABEL_CHFJPY")
        self.gridLayout_4.addWidget(self.LABEL_CHFJPY, 8, 0, 1, 1)
        self.LABEL_CADCHF = QtWidgets.QLabel(Dialog)
        self.LABEL_CADCHF.setObjectName("LABEL_CADCHF")
        self.gridLayout_4.addWidget(self.LABEL_CADCHF, 6, 0, 1, 1)
        self.LABEL_EURJPY = QtWidgets.QLabel(Dialog)
        self.LABEL_EURJPY.setObjectName("LABEL_EURJPY")
        self.gridLayout_4.addWidget(self.LABEL_EURJPY, 13, 0, 1, 1)
        self.LABEL_EURAUD = QtWidgets.QLabel(Dialog)
        self.LABEL_EURAUD.setObjectName("LABEL_EURAUD")
        self.gridLayout_4.addWidget(self.LABEL_EURAUD, 9, 0, 1, 1)
        self.LABEL_NZDCAD = QtWidgets.QLabel(Dialog)
        self.LABEL_NZDCAD.setObjectName("LABEL_NZDCAD")
        self.gridLayout_4.addWidget(self.LABEL_NZDCAD, 22, 0, 1, 1)
        self.LABEL_GBPUSD = QtWidgets.QLabel(Dialog)
        self.LABEL_GBPUSD.setObjectName("LABEL_GBPUSD")
        self.gridLayout_4.addWidget(self.LABEL_GBPUSD, 21, 0, 1, 1)
        self.LABEL_NZDCHF = QtWidgets.QLabel(Dialog)
        self.LABEL_NZDCHF.setObjectName("LABEL_NZDCHF")
        self.gridLayout_4.addWidget(self.LABEL_NZDCHF, 23, 0, 1, 1)
        self.LABEL_EURUSD = QtWidgets.QLabel(Dialog)
        self.LABEL_EURUSD.setObjectName("LABEL_EURUSD")
        self.gridLayout_4.addWidget(self.LABEL_EURUSD, 15, 0, 1, 1)
        self.LABEL_NZDJPY = QtWidgets.QLabel(Dialog)
        self.LABEL_NZDJPY.setObjectName("LABEL_NZDJPY")
        self.gridLayout_4.addWidget(self.LABEL_NZDJPY, 24, 0, 1, 1)
        self.LABEL_AUDCHF = QtWidgets.QLabel(Dialog)
        self.LABEL_AUDCHF.setObjectName("LABEL_AUDCHF")
        self.gridLayout_4.addWidget(self.LABEL_AUDCHF, 2, 0, 1, 1)
        self.LABEL_EURGBP = QtWidgets.QLabel(Dialog)
        self.LABEL_EURGBP.setObjectName("LABEL_EURGBP")
        self.gridLayout_4.addWidget(self.LABEL_EURGBP, 12, 0, 1, 1)
        self.LABEL_GBPAUD = QtWidgets.QLabel(Dialog)
        self.LABEL_GBPAUD.setObjectName("LABEL_GBPAUD")
        self.gridLayout_4.addWidget(self.LABEL_GBPAUD, 16, 0, 1, 1)
        self.LABEL_GBPCAD = QtWidgets.QLabel(Dialog)
        self.LABEL_GBPCAD.setObjectName("LABEL_GBPCAD")
        self.gridLayout_4.addWidget(self.LABEL_GBPCAD, 17, 0, 1, 1)
        self.LABEL_NZDUSD = QtWidgets.QLabel(Dialog)
        self.LABEL_NZDUSD.setObjectName("LABEL_NZDUSD")
        self.gridLayout_4.addWidget(self.LABEL_NZDUSD, 25, 0, 1, 1)
        self.LABEL_USDCAD = QtWidgets.QLabel(Dialog)
        self.LABEL_USDCAD.setObjectName("LABEL_USDCAD")
        self.gridLayout_4.addWidget(self.LABEL_USDCAD, 26, 0, 1, 1)
        self.LABEL_USDCHF = QtWidgets.QLabel(Dialog)
        self.LABEL_USDCHF.setObjectName("LABEL_USDCHF")
        self.gridLayout_4.addWidget(self.LABEL_USDCHF, 27, 0, 1, 1)
        self.LABEL_USDJPY = QtWidgets.QLabel(Dialog)
        self.LABEL_USDJPY.setObjectName("LABEL_USDJPY")
        self.gridLayout_4.addWidget(self.LABEL_USDJPY, 28, 0, 1, 1)
        self.range20min5title = QtWidgets.QLabel(Dialog)
        self.range20min5title.setObjectName("range20min5title")
        self.gridLayout_4.addWidget(self.range20min5title, 0, 1, 1, 1)
        self.range20min5_AUDCAD = QtWidgets.QLabel(Dialog)
        self.range20min5_AUDCAD.setObjectName("range20min5_AUDCAD")
        self.gridLayout_4.addWidget(self.range20min5_AUDCAD, 1, 1, 1, 1)
        self.range20min5_AUDCHF = QtWidgets.QLabel(Dialog)
        self.range20min5_AUDCHF.setObjectName("range20min5_AUDCHF")
        self.gridLayout_4.addWidget(self.range20min5_AUDCHF, 2, 1, 1, 1)
        self.range20min5_AUDJPY = QtWidgets.QLabel(Dialog)
        self.range20min5_AUDJPY.setObjectName("range20min5_AUDJPY")
        self.gridLayout_4.addWidget(self.range20min5_AUDJPY, 3, 1, 1, 1)
        self.range20min5_AUDNZD = QtWidgets.QLabel(Dialog)
        self.range20min5_AUDNZD.setObjectName("range20min5_AUDNZD")
        self.gridLayout_4.addWidget(self.range20min5_AUDNZD, 4, 1, 1, 1)
        self.range20min5_AUDUSD = QtWidgets.QLabel(Dialog)
        self.range20min5_AUDUSD.setObjectName("range20min5_AUDUSD")
        self.gridLayout_4.addWidget(self.range20min5_AUDUSD, 5, 1, 1, 1)
        self.range20min5_CADCHF = QtWidgets.QLabel(Dialog)
        self.range20min5_CADCHF.setObjectName("range20min5_CADCHF")
        self.gridLayout_4.addWidget(self.range20min5_CADCHF, 6, 1, 1, 1)
        self.range20min5_CADJPY = QtWidgets.QLabel(Dialog)
        self.range20min5_CADJPY.setObjectName("range20min5_CADJPY")
        self.gridLayout_4.addWidget(self.range20min5_CADJPY, 7, 1, 1, 1)
        self.range20min5_CHFJPY = QtWidgets.QLabel(Dialog)
        self.range20min5_CHFJPY.setObjectName("range20min5_CHFJPY")
        self.gridLayout_4.addWidget(self.range20min5_CHFJPY, 8, 1, 1, 1)
        self.range20min5_EURAUD = QtWidgets.QLabel(Dialog)
        self.range20min5_EURAUD.setObjectName("range20min5_EURAUD")
        self.gridLayout_4.addWidget(self.range20min5_EURAUD, 9, 1, 1, 1)
        self.range20min5_EURCAD = QtWidgets.QLabel(Dialog)
        self.range20min5_EURCAD.setObjectName("range20min5_EURCAD")
        self.gridLayout_4.addWidget(self.range20min5_EURCAD, 10, 1, 1, 1)
        self.range20min5_EURCHF = QtWidgets.QLabel(Dialog)
        self.range20min5_EURCHF.setObjectName("range20min5_EURCHF")
        self.gridLayout_4.addWidget(self.range20min5_EURCHF, 11, 1, 1, 1)
        self.range20min5_EURGBP = QtWidgets.QLabel(Dialog)
        self.range20min5_EURGBP.setObjectName("range20min5_EURGBP")
        self.gridLayout_4.addWidget(self.range20min5_EURGBP, 12, 1, 1, 1)
        self.range20min5_EURJPY = QtWidgets.QLabel(Dialog)
        self.range20min5_EURJPY.setObjectName("range20min5_EURJPY")
        self.gridLayout_4.addWidget(self.range20min5_EURJPY, 13, 1, 1, 1)
        self.range20min5_EURNZD = QtWidgets.QLabel(Dialog)
        self.range20min5_EURNZD.setObjectName("range20min5_EURNZD")
        self.gridLayout_4.addWidget(self.range20min5_EURNZD, 14, 1, 1, 1)
        self.range20min5_EURUSD = QtWidgets.QLabel(Dialog)
        self.range20min5_EURUSD.setObjectName("range20min5_EURUSD")
        self.gridLayout_4.addWidget(self.range20min5_EURUSD, 15, 1, 1, 1)
        self.range20min5_GBPAUD = QtWidgets.QLabel(Dialog)
        self.range20min5_GBPAUD.setObjectName("range20min5_GBPAUD")
        self.gridLayout_4.addWidget(self.range20min5_GBPAUD, 16, 1, 1, 1)
        self.range20min5_GBPCAD = QtWidgets.QLabel(Dialog)
        self.range20min5_GBPCAD.setObjectName("range20min5_GBPCAD")
        self.gridLayout_4.addWidget(self.range20min5_GBPCAD, 17, 1, 1, 1)
        self.range20min5_GBPCHF = QtWidgets.QLabel(Dialog)
        self.range20min5_GBPCHF.setObjectName("range20min5_GBPCHF")
        self.gridLayout_4.addWidget(self.range20min5_GBPCHF, 18, 1, 1, 1)
        self.range20min5_GBPJPY = QtWidgets.QLabel(Dialog)
        self.range20min5_GBPJPY.setObjectName("range20min5_GBPJPY")
        self.gridLayout_4.addWidget(self.range20min5_GBPJPY, 19, 1, 1, 1)
        self.range20min5_GBPNZD = QtWidgets.QLabel(Dialog)
        self.range20min5_GBPNZD.setObjectName("range20min5_GBPNZD")
        self.gridLayout_4.addWidget(self.range20min5_GBPNZD, 20, 1, 1, 1)
        self.range20min5_GBPUSD = QtWidgets.QLabel(Dialog)
        self.range20min5_GBPUSD.setObjectName("range20min5_GBPUSD")
        self.gridLayout_4.addWidget(self.range20min5_GBPUSD, 21, 1, 1, 1)
        self.range20min5_NZDCAD = QtWidgets.QLabel(Dialog)
        self.range20min5_NZDCAD.setObjectName("range20min5_NZDCAD")
        self.gridLayout_4.addWidget(self.range20min5_NZDCAD, 22, 1, 1, 1)
        self.range20min5_NZDCHF = QtWidgets.QLabel(Dialog)
        self.range20min5_NZDCHF.setObjectName("range20min5_NZDCHF")
        self.gridLayout_4.addWidget(self.range20min5_NZDCHF, 23, 1, 1, 1)
        self.range20min5_NZDJPY = QtWidgets.QLabel(Dialog)
        self.range20min5_NZDJPY.setObjectName("range20min5_NZDJPY")
        self.gridLayout_4.addWidget(self.range20min5_NZDJPY, 24, 1, 1, 1)
        self.range20min5_NZDUSD = QtWidgets.QLabel(Dialog)
        self.range20min5_NZDUSD.setObjectName("range20min5_NZDUSD")
        self.gridLayout_4.addWidget(self.range20min5_NZDUSD, 25, 1, 1, 1)
        self.range20min5_USDCAD = QtWidgets.QLabel(Dialog)
        self.range20min5_USDCAD.setObjectName("range20min5_USDCAD")
        self.gridLayout_4.addWidget(self.range20min5_USDCAD, 26, 1, 1, 1)
        self.range20min5_USDCHF = QtWidgets.QLabel(Dialog)
        self.range20min5_USDCHF.setObjectName("range20min5_USDCHF")
        self.gridLayout_4.addWidget(self.range20min5_USDCHF, 27, 1, 1, 1)
        self.range20min5_USDJPY = QtWidgets.QLabel(Dialog)
        self.range20min5_USDJPY.setObjectName("range20min5_USDJPY")
        self.gridLayout_4.addWidget(self.range20min5_USDJPY, 28, 1, 1, 1)
        self.range20min15title = QtWidgets.QLabel(Dialog)
        self.range20min15title.setObjectName("range20min15title")
        self.gridLayout_4.addWidget(self.range20min15title, 0, 2, 1, 1)
        self.range20min15_AUDCAD = QtWidgets.QLabel(Dialog)
        self.range20min15_AUDCAD.setObjectName("range20min15_AUDCAD")
        self.gridLayout_4.addWidget(self.range20min15_AUDCAD, 1, 2, 1, 1)
        self.range20min15_AUDCHF = QtWidgets.QLabel(Dialog)
        self.range20min15_AUDCHF.setObjectName("range20min15_AUDCHF")
        self.gridLayout_4.addWidget(self.range20min15_AUDCHF, 2, 2, 1, 1)
        self.range20min15_AUDJPY = QtWidgets.QLabel(Dialog)
        self.range20min15_AUDJPY.setObjectName("range20min15_AUDJPY")
        self.gridLayout_4.addWidget(self.range20min15_AUDJPY, 3, 2, 1, 1)
        self.range20min15_AUDNZD = QtWidgets.QLabel(Dialog)
        self.range20min15_AUDNZD.setObjectName("range20min15_AUDNZD")
        self.gridLayout_4.addWidget(self.range20min15_AUDNZD, 4, 2, 1, 1)
        self.range20min15_AUDUSD = QtWidgets.QLabel(Dialog)
        self.range20min15_AUDUSD.setObjectName("range20min15_AUDUSD")
        self.gridLayout_4.addWidget(self.range20min15_AUDUSD, 5, 2, 1, 1)
        self.range20min15_CADCHF = QtWidgets.QLabel(Dialog)
        self.range20min15_CADCHF.setObjectName("range20min15_CADCHF")
        self.gridLayout_4.addWidget(self.range20min15_CADCHF, 6, 2, 1, 1)
        self.range20min15_CADJPY = QtWidgets.QLabel(Dialog)
        self.range20min15_CADJPY.setObjectName("range20min15_CADJPY")
        self.gridLayout_4.addWidget(self.range20min15_CADJPY, 7, 2, 1, 1)
        self.range20min15_CHFJPY = QtWidgets.QLabel(Dialog)
        self.range20min15_CHFJPY.setObjectName("range20min15_CHFJPY")
        self.gridLayout_4.addWidget(self.range20min15_CHFJPY, 8, 2, 1, 1)
        self.range20min15_EURAUD = QtWidgets.QLabel(Dialog)
        self.range20min15_EURAUD.setObjectName("range20min15_EURAUD")
        self.gridLayout_4.addWidget(self.range20min15_EURAUD, 9, 2, 1, 1)
        self.range20min15_EURCAD = QtWidgets.QLabel(Dialog)
        self.range20min15_EURCAD.setObjectName("range20min15_EURCAD")
        self.gridLayout_4.addWidget(self.range20min15_EURCAD, 10, 2, 1, 1)
        self.range20min15_EURCHF = QtWidgets.QLabel(Dialog)
        self.range20min15_EURCHF.setObjectName("range20min15_EURCHF")
        self.gridLayout_4.addWidget(self.range20min15_EURCHF, 11, 2, 1, 1)
        self.range20min15_EURGBP = QtWidgets.QLabel(Dialog)
        self.range20min15_EURGBP.setObjectName("range20min15_EURGBP")
        self.gridLayout_4.addWidget(self.range20min15_EURGBP, 12, 2, 1, 1)
        self.range20min15_EURJPY = QtWidgets.QLabel(Dialog)
        self.range20min15_EURJPY.setObjectName("range20min15_EURJPY")
        self.gridLayout_4.addWidget(self.range20min15_EURJPY, 13, 2, 1, 1)
        self.range20min15_EURNZD = QtWidgets.QLabel(Dialog)
        self.range20min15_EURNZD.setObjectName("range20min15_EURNZD")
        self.gridLayout_4.addWidget(self.range20min15_EURNZD, 14, 2, 1, 1)
        self.range20min15_EURUSD = QtWidgets.QLabel(Dialog)
        self.range20min15_EURUSD.setObjectName("range20min15_EURUSD")
        self.gridLayout_4.addWidget(self.range20min15_EURUSD, 15, 2, 1, 1)
        self.range20min15_GBPAUD = QtWidgets.QLabel(Dialog)
        self.range20min15_GBPAUD.setObjectName("range20min15_GBPAUD")
        self.gridLayout_4.addWidget(self.range20min15_GBPAUD, 16, 2, 1, 1)
        self.range20min15_GBPCAD = QtWidgets.QLabel(Dialog)
        self.range20min15_GBPCAD.setObjectName("range20min15_GBPCAD")
        self.gridLayout_4.addWidget(self.range20min15_GBPCAD, 17, 2, 1, 1)
        self.range20min15_GBPCHF = QtWidgets.QLabel(Dialog)
        self.range20min15_GBPCHF.setObjectName("range20min15_GBPCHF")
        self.gridLayout_4.addWidget(self.range20min15_GBPCHF, 18, 2, 1, 1)
        self.range20min15_GBPJPY = QtWidgets.QLabel(Dialog)
        self.range20min15_GBPJPY.setObjectName("range20min15_GBPJPY")
        self.gridLayout_4.addWidget(self.range20min15_GBPJPY, 19, 2, 1, 1)
        self.range20min15_GBPNZD = QtWidgets.QLabel(Dialog)
        self.range20min15_GBPNZD.setObjectName("range20min15_GBPNZD")
        self.gridLayout_4.addWidget(self.range20min15_GBPNZD, 20, 2, 1, 1)
        self.range20min15_GBPUSD = QtWidgets.QLabel(Dialog)
        self.range20min15_GBPUSD.setObjectName("range20min15_GBPUSD")
        self.gridLayout_4.addWidget(self.range20min15_GBPUSD, 21, 2, 1, 1)
        self.range20min15_NZDCAD = QtWidgets.QLabel(Dialog)
        self.range20min15_NZDCAD.setObjectName("range20min15_NZDCAD")
        self.gridLayout_4.addWidget(self.range20min15_NZDCAD, 22, 2, 1, 1)
        self.range20min15_NZDCHF = QtWidgets.QLabel(Dialog)
        self.range20min15_NZDCHF.setObjectName("range20min15_NZDCHF")
        self.gridLayout_4.addWidget(self.range20min15_NZDCHF, 23, 2, 1, 1)
        self.range20min15_NZDJPY = QtWidgets.QLabel(Dialog)
        self.range20min15_NZDJPY.setObjectName("range20min15_NZDJPY")
        self.gridLayout_4.addWidget(self.range20min15_NZDJPY, 24, 2, 1, 1)
        self.range20min15_NZDUSD = QtWidgets.QLabel(Dialog)
        self.range20min15_NZDUSD.setObjectName("range20min15_NZDUSD")
        self.gridLayout_4.addWidget(self.range20min15_NZDUSD, 25, 2, 1, 1)
        self.range20min15_USDCAD = QtWidgets.QLabel(Dialog)
        self.range20min15_USDCAD.setObjectName("range20min15_USDCAD")
        self.gridLayout_4.addWidget(self.range20min15_USDCAD, 26, 2, 1, 1)
        self.range20min15_USDCHF = QtWidgets.QLabel(Dialog)
        self.range20min15_USDCHF.setObjectName("range20min15_USDCHF")
        self.gridLayout_4.addWidget(self.range20min15_USDCHF, 27, 2, 1, 1)
        self.range20min15_USDJPY = QtWidgets.QLabel(Dialog)
        self.range20min15_USDJPY.setObjectName("range20min15_USDJPY")
        self.gridLayout_4.addWidget(self.range20min15_USDJPY, 28, 2, 1, 1)
        self.tsi5title = QtWidgets.QLabel(Dialog)
        self.tsi5title.setObjectName("tsi5title")
        self.gridLayout_4.addWidget(self.tsi5title, 0, 3, 1, 1)
        self.tsi5_AUDCAD = QtWidgets.QLabel(Dialog)
        self.tsi5_AUDCAD.setObjectName("tsi5_AUDCAD")
        self.gridLayout_4.addWidget(self.tsi5_AUDCAD, 1, 3, 1, 1)
        self.tsi5_AUDCHF = QtWidgets.QLabel(Dialog)
        self.tsi5_AUDCHF.setObjectName("tsi5_AUDCHF")
        self.gridLayout_4.addWidget(self.tsi5_AUDCHF, 2, 3, 1, 1)
        self.tsi5_AUDJPY = QtWidgets.QLabel(Dialog)
        self.tsi5_AUDJPY.setObjectName("tsi5_AUDJPY")
        self.gridLayout_4.addWidget(self.tsi5_AUDJPY, 3, 3, 1, 1)
        self.tsi5_AUDNZD = QtWidgets.QLabel(Dialog)
        self.tsi5_AUDNZD.setObjectName("tsi5_AUDNZD")
        self.gridLayout_4.addWidget(self.tsi5_AUDNZD, 4, 3, 1, 1)
        self.tsi5_AUDUSD = QtWidgets.QLabel(Dialog)
        self.tsi5_AUDUSD.setObjectName("tsi5_AUDUSD")
        self.gridLayout_4.addWidget(self.tsi5_AUDUSD, 5, 3, 1, 1)
        self.tsi5_CADCHF = QtWidgets.QLabel(Dialog)
        self.tsi5_CADCHF.setObjectName("tsi5_CADCHF")
        self.gridLayout_4.addWidget(self.tsi5_CADCHF, 6, 3, 1, 1)
        self.tsi5_CADJPY = QtWidgets.QLabel(Dialog)
        self.tsi5_CADJPY.setObjectName("tsi5_CADJPY")
        self.gridLayout_4.addWidget(self.tsi5_CADJPY, 7, 3, 1, 1)
        self.tsi5_CHFJPY = QtWidgets.QLabel(Dialog)
        self.tsi5_CHFJPY.setObjectName("tsi5_CHFJPY")
        self.gridLayout_4.addWidget(self.tsi5_CHFJPY, 8, 3, 1, 1)
        self.tsi5_EURAUD = QtWidgets.QLabel(Dialog)
        self.tsi5_EURAUD.setObjectName("tsi5_EURAUD")
        self.gridLayout_4.addWidget(self.tsi5_EURAUD, 9, 3, 1, 1)
        self.tsi5_EURCAD = QtWidgets.QLabel(Dialog)
        self.tsi5_EURCAD.setObjectName("tsi5_EURCAD")
        self.gridLayout_4.addWidget(self.tsi5_EURCAD, 10, 3, 1, 1)
        self.tsi5_EURCHF = QtWidgets.QLabel(Dialog)
        self.tsi5_EURCHF.setObjectName("tsi5_EURCHF")
        self.gridLayout_4.addWidget(self.tsi5_EURCHF, 11, 3, 1, 1)
        self.tsi5_EURGBP = QtWidgets.QLabel(Dialog)
        self.tsi5_EURGBP.setObjectName("tsi5_EURGBP")
        self.gridLayout_4.addWidget(self.tsi5_EURGBP, 12, 3, 1, 1)
        self.tsi5_EURJPY = QtWidgets.QLabel(Dialog)
        self.tsi5_EURJPY.setObjectName("tsi5_EURJPY")
        self.gridLayout_4.addWidget(self.tsi5_EURJPY, 13, 3, 1, 1)
        self.tsi5_EURNZD = QtWidgets.QLabel(Dialog)
        self.tsi5_EURNZD.setObjectName("tsi5_EURNZD")
        self.gridLayout_4.addWidget(self.tsi5_EURNZD, 14, 3, 1, 1)
        self.tsi5_EURUSD = QtWidgets.QLabel(Dialog)
        self.tsi5_EURUSD.setObjectName("tsi5_EURUSD")
        self.gridLayout_4.addWidget(self.tsi5_EURUSD, 15, 3, 1, 1)
        self.tsi5_GBPAUD = QtWidgets.QLabel(Dialog)
        self.tsi5_GBPAUD.setObjectName("tsi5_GBPAUD")
        self.gridLayout_4.addWidget(self.tsi5_GBPAUD, 16, 3, 1, 1)
        self.tsi5_GBPCAD = QtWidgets.QLabel(Dialog)
        self.tsi5_GBPCAD.setObjectName("tsi5_GBPCAD")
        self.gridLayout_4.addWidget(self.tsi5_GBPCAD, 17, 3, 1, 1)
        self.tsi5_GBPCHF = QtWidgets.QLabel(Dialog)
        self.tsi5_GBPCHF.setObjectName("tsi5_GBPCHF")
        self.gridLayout_4.addWidget(self.tsi5_GBPCHF, 18, 3, 1, 1)
        self.tsi5_GBPJPY = QtWidgets.QLabel(Dialog)
        self.tsi5_GBPJPY.setObjectName("tsi5_GBPJPY")
        self.gridLayout_4.addWidget(self.tsi5_GBPJPY, 19, 3, 1, 1)
        self.tsi5_GBPNZD = QtWidgets.QLabel(Dialog)
        self.tsi5_GBPNZD.setObjectName("tsi5_GBPNZD")
        self.gridLayout_4.addWidget(self.tsi5_GBPNZD, 20, 3, 1, 1)
        self.tsi5_GBPUSD = QtWidgets.QLabel(Dialog)
        self.tsi5_GBPUSD.setObjectName("tsi5_GBPUSD")
        self.gridLayout_4.addWidget(self.tsi5_GBPUSD, 21, 3, 1, 1)
        self.tsi5_NZDCAD = QtWidgets.QLabel(Dialog)
        self.tsi5_NZDCAD.setObjectName("tsi5_NZDCAD")
        self.gridLayout_4.addWidget(self.tsi5_NZDCAD, 22, 3, 1, 1)
        self.tsi5_NZDCHF = QtWidgets.QLabel(Dialog)
        self.tsi5_NZDCHF.setObjectName("tsi5_NZDCHF")
        self.gridLayout_4.addWidget(self.tsi5_NZDCHF, 23, 3, 1, 1)
        self.tsi5_NZDJPY = QtWidgets.QLabel(Dialog)
        self.tsi5_NZDJPY.setObjectName("tsi5_NZDJPY")
        self.gridLayout_4.addWidget(self.tsi5_NZDJPY, 24, 3, 1, 1)
        self.tsi5_NZDUSD = QtWidgets.QLabel(Dialog)
        self.tsi5_NZDUSD.setObjectName("tsi5_NZDUSD")
        self.gridLayout_4.addWidget(self.tsi5_NZDUSD, 25, 3, 1, 1)
        self.tsi5_USDCAD = QtWidgets.QLabel(Dialog)
        self.tsi5_USDCAD.setObjectName("tsi5_USDCAD")
        self.gridLayout_4.addWidget(self.tsi5_USDCAD, 26, 3, 1, 1)
        self.tsi5_USDCHF = QtWidgets.QLabel(Dialog)
        self.tsi5_USDCHF.setObjectName("tsi5_USDCHF")
        self.gridLayout_4.addWidget(self.tsi5_USDCHF, 27, 3, 1, 1)
        self.tsi5_USDJPY = QtWidgets.QLabel(Dialog)
        self.tsi5_USDJPY.setObjectName("tsi5_USDJPY")
        self.gridLayout_4.addWidget(self.tsi5_USDJPY, 28, 3, 1, 1)
        self.tsi15title = QtWidgets.QLabel(Dialog)
        self.tsi15title.setObjectName("tsi15title")
        self.gridLayout_4.addWidget(self.tsi15title, 0, 4, 1, 1)
        self.tsi15_AUDCAD = QtWidgets.QLabel(Dialog)
        self.tsi15_AUDCAD.setObjectName("tsi15_AUDCAD")
        self.gridLayout_4.addWidget(self.tsi15_AUDCAD, 1, 4, 1, 1)
        self.tsi15_AUDCHF = QtWidgets.QLabel(Dialog)
        self.tsi15_AUDCHF.setObjectName("tsi15_AUDCHF")
        self.gridLayout_4.addWidget(self.tsi15_AUDCHF, 2, 4, 1, 1)
        self.tsi15_AUDJPY = QtWidgets.QLabel(Dialog)
        self.tsi15_AUDJPY.setObjectName("tsi15_AUDJPY")
        self.gridLayout_4.addWidget(self.tsi15_AUDJPY, 3, 4, 1, 1)
        self.tsi15_AUDNZD = QtWidgets.QLabel(Dialog)
        self.tsi15_AUDNZD.setObjectName("tsi15_AUDNZD")
        self.gridLayout_4.addWidget(self.tsi15_AUDNZD, 4, 4, 1, 1)
        self.tsi15_AUDUSD = QtWidgets.QLabel(Dialog)
        self.tsi15_AUDUSD.setObjectName("tsi15_AUDUSD")
        self.gridLayout_4.addWidget(self.tsi15_AUDUSD, 5, 4, 1, 1)
        self.tsi15_CADCHF = QtWidgets.QLabel(Dialog)
        self.tsi15_CADCHF.setObjectName("tsi15_CADCHF")
        self.gridLayout_4.addWidget(self.tsi15_CADCHF, 6, 4, 1, 1)
        self.tsi15_CADJPY = QtWidgets.QLabel(Dialog)
        self.tsi15_CADJPY.setObjectName("tsi15_CADJPY")
        self.gridLayout_4.addWidget(self.tsi15_CADJPY, 7, 4, 1, 1)
        self.tsi15_CHFJPY = QtWidgets.QLabel(Dialog)
        self.tsi15_CHFJPY.setObjectName("tsi15_CHFJPY")
        self.gridLayout_4.addWidget(self.tsi15_CHFJPY, 8, 4, 1, 1)
        self.tsi15_EURAUD = QtWidgets.QLabel(Dialog)
        self.tsi15_EURAUD.setObjectName("tsi15_EURAUD")
        self.gridLayout_4.addWidget(self.tsi15_EURAUD, 9, 4, 1, 1)
        self.tsi15_EURCAD = QtWidgets.QLabel(Dialog)
        self.tsi15_EURCAD.setObjectName("tsi15_EURCAD")
        self.gridLayout_4.addWidget(self.tsi15_EURCAD, 10, 4, 1, 1)
        self.tsi15_EURCHF = QtWidgets.QLabel(Dialog)
        self.tsi15_EURCHF.setObjectName("tsi15_EURCHF")
        self.gridLayout_4.addWidget(self.tsi15_EURCHF, 11, 4, 1, 1)
        self.tsi15_EURGBP = QtWidgets.QLabel(Dialog)
        self.tsi15_EURGBP.setObjectName("tsi15_EURGBP")
        self.gridLayout_4.addWidget(self.tsi15_EURGBP, 12, 4, 1, 1)
        self.tsi15_EURJPY = QtWidgets.QLabel(Dialog)
        self.tsi15_EURJPY.setObjectName("tsi15_EURJPY")
        self.gridLayout_4.addWidget(self.tsi15_EURJPY, 13, 4, 1, 1)
        self.tsi15_EURNZD = QtWidgets.QLabel(Dialog)
        self.tsi15_EURNZD.setObjectName("tsi15_EURNZD")
        self.gridLayout_4.addWidget(self.tsi15_EURNZD, 14, 4, 1, 1)
        self.tsi15_EURUSD = QtWidgets.QLabel(Dialog)
        self.tsi15_EURUSD.setObjectName("tsi15_EURUSD")
        self.gridLayout_4.addWidget(self.tsi15_EURUSD, 15, 4, 1, 1)
        self.tsi15_GBPAUD = QtWidgets.QLabel(Dialog)
        self.tsi15_GBPAUD.setObjectName("tsi15_GBPAUD")
        self.gridLayout_4.addWidget(self.tsi15_GBPAUD, 16, 4, 1, 1)
        self.tsi15_GBPCAD = QtWidgets.QLabel(Dialog)
        self.tsi15_GBPCAD.setObjectName("tsi15_GBPCAD")
        self.gridLayout_4.addWidget(self.tsi15_GBPCAD, 17, 4, 1, 1)
        self.tsi15_GBPCHF = QtWidgets.QLabel(Dialog)
        self.tsi15_GBPCHF.setObjectName("tsi15_GBPCHF")
        self.gridLayout_4.addWidget(self.tsi15_GBPCHF, 18, 4, 1, 1)
        self.tsi15_GBPJPY = QtWidgets.QLabel(Dialog)
        self.tsi15_GBPJPY.setObjectName("tsi15_GBPJPY")
        self.gridLayout_4.addWidget(self.tsi15_GBPJPY, 19, 4, 1, 1)
        self.tsi15_GBPNZD = QtWidgets.QLabel(Dialog)
        self.tsi15_GBPNZD.setObjectName("tsi15_GBPNZD")
        self.gridLayout_4.addWidget(self.tsi15_GBPNZD, 20, 4, 1, 1)
        self.tsi15_GBPUSD = QtWidgets.QLabel(Dialog)
        self.tsi15_GBPUSD.setObjectName("tsi15_GBPUSD")
        self.gridLayout_4.addWidget(self.tsi15_GBPUSD, 21, 4, 1, 1)
        self.tsi15_NZDCAD = QtWidgets.QLabel(Dialog)
        self.tsi15_NZDCAD.setObjectName("tsi15_NZDCAD")
        self.gridLayout_4.addWidget(self.tsi15_NZDCAD, 22, 4, 1, 1)
        self.tsi15_NZDCHF = QtWidgets.QLabel(Dialog)
        self.tsi15_NZDCHF.setObjectName("tsi15_NZDCHF")
        self.gridLayout_4.addWidget(self.tsi15_NZDCHF, 23, 4, 1, 1)
        self.tsi15_NZDJPY = QtWidgets.QLabel(Dialog)
        self.tsi15_NZDJPY.setObjectName("tsi15_NZDJPY")
        self.gridLayout_4.addWidget(self.tsi15_NZDJPY, 24, 4, 1, 1)
        self.tsi15_NZDUSD = QtWidgets.QLabel(Dialog)
        self.tsi15_NZDUSD.setObjectName("tsi15_NZDUSD")
        self.gridLayout_4.addWidget(self.tsi15_NZDUSD, 25, 4, 1, 1)
        self.tsi15_USDCAD = QtWidgets.QLabel(Dialog)
        self.tsi15_USDCAD.setObjectName("tsi15_USDCAD")
        self.gridLayout_4.addWidget(self.tsi15_USDCAD, 26, 4, 1, 1)
        self.tsi15_USDCHF = QtWidgets.QLabel(Dialog)
        self.tsi15_USDCHF.setObjectName("tsi15_USDCHF")
        self.gridLayout_4.addWidget(self.tsi15_USDCHF, 27, 4, 1, 1)
        self.tsi15_USDJPY = QtWidgets.QLabel(Dialog)
        self.tsi15_USDJPY.setObjectName("tsi15_USDJPY")
        self.gridLayout_4.addWidget(self.tsi15_USDJPY, 28, 4, 1, 1)
        self.tsi60title = QtWidgets.QLabel(Dialog)
        self.tsi60title.setObjectName("tsi60title")
        self.gridLayout_4.addWidget(self.tsi60title, 0, 5, 1, 1)
        self.tsi60_AUDCAD = QtWidgets.QLabel(Dialog)
        self.tsi60_AUDCAD.setObjectName("tsi60_AUDCAD")
        self.gridLayout_4.addWidget(self.tsi60_AUDCAD, 1, 5, 1, 1)
        self.tsi60_AUDCHF = QtWidgets.QLabel(Dialog)
        self.tsi60_AUDCHF.setObjectName("tsi60_AUDCHF")
        self.gridLayout_4.addWidget(self.tsi60_AUDCHF, 2, 5, 1, 1)
        self.tsi60_AUDJPY = QtWidgets.QLabel(Dialog)
        self.tsi60_AUDJPY.setObjectName("tsi60_AUDJPY")
        self.gridLayout_4.addWidget(self.tsi60_AUDJPY, 3, 5, 1, 1)
        self.tsi60_AUDNZD = QtWidgets.QLabel(Dialog)
        self.tsi60_AUDNZD.setObjectName("tsi60_AUDNZD")
        self.gridLayout_4.addWidget(self.tsi60_AUDNZD, 4, 5, 1, 1)
        self.tsi60_AUDUSD = QtWidgets.QLabel(Dialog)
        self.tsi60_AUDUSD.setObjectName("tsi60_AUDUSD")
        self.gridLayout_4.addWidget(self.tsi60_AUDUSD, 5, 5, 1, 1)
        self.tsi60_CADCHF = QtWidgets.QLabel(Dialog)
        self.tsi60_CADCHF.setObjectName("tsi60_CADCHF")
        self.gridLayout_4.addWidget(self.tsi60_CADCHF, 6, 5, 1, 1)
        self.tsi60_CADJPY = QtWidgets.QLabel(Dialog)
        self.tsi60_CADJPY.setObjectName("tsi60_CADJPY")
        self.gridLayout_4.addWidget(self.tsi60_CADJPY, 7, 5, 1, 1)
        self.tsi60_CHFJPY = QtWidgets.QLabel(Dialog)
        self.tsi60_CHFJPY.setObjectName("tsi60_CHFJPY")
        self.gridLayout_4.addWidget(self.tsi60_CHFJPY, 8, 5, 1, 1)
        self.tsi60_EURAUD = QtWidgets.QLabel(Dialog)
        self.tsi60_EURAUD.setObjectName("tsi60_EURAUD")
        self.gridLayout_4.addWidget(self.tsi60_EURAUD, 9, 5, 1, 1)
        self.tsi60_EURCAD = QtWidgets.QLabel(Dialog)
        self.tsi60_EURCAD.setObjectName("tsi60_EURCAD")
        self.gridLayout_4.addWidget(self.tsi60_EURCAD, 10, 5, 1, 1)
        self.tsi60_EURCHF = QtWidgets.QLabel(Dialog)
        self.tsi60_EURCHF.setObjectName("tsi60_EURCHF")
        self.gridLayout_4.addWidget(self.tsi60_EURCHF, 11, 5, 1, 1)
        self.tsi60_EURGBP = QtWidgets.QLabel(Dialog)
        self.tsi60_EURGBP.setObjectName("tsi60_EURGBP")
        self.gridLayout_4.addWidget(self.tsi60_EURGBP, 12, 5, 1, 1)
        self.tsi60_EURJPY = QtWidgets.QLabel(Dialog)
        self.tsi60_EURJPY.setObjectName("tsi60_EURJPY")
        self.gridLayout_4.addWidget(self.tsi60_EURJPY, 13, 5, 1, 1)
        self.tsi60_EURNZD = QtWidgets.QLabel(Dialog)
        self.tsi60_EURNZD.setObjectName("tsi60_EURNZD")
        self.gridLayout_4.addWidget(self.tsi60_EURNZD, 14, 5, 1, 1)
        self.tsi60_EURUSD = QtWidgets.QLabel(Dialog)
        self.tsi60_EURUSD.setObjectName("tsi60_EURUSD")
        self.gridLayout_4.addWidget(self.tsi60_EURUSD, 15, 5, 1, 1)
        self.tsi60_GBPAUD = QtWidgets.QLabel(Dialog)
        self.tsi60_GBPAUD.setObjectName("tsi60_GBPAUD")
        self.gridLayout_4.addWidget(self.tsi60_GBPAUD, 16, 5, 1, 1)
        self.tsi60_GBPCAD = QtWidgets.QLabel(Dialog)
        self.tsi60_GBPCAD.setObjectName("tsi60_GBPCAD")
        self.gridLayout_4.addWidget(self.tsi60_GBPCAD, 17, 5, 1, 1)
        self.tsi60_GBPCHF = QtWidgets.QLabel(Dialog)
        self.tsi60_GBPCHF.setObjectName("tsi60_GBPCHF")
        self.gridLayout_4.addWidget(self.tsi60_GBPCHF, 18, 5, 1, 1)
        self.tsi60_GBPJPY = QtWidgets.QLabel(Dialog)
        self.tsi60_GBPJPY.setObjectName("tsi60_GBPJPY")
        self.gridLayout_4.addWidget(self.tsi60_GBPJPY, 19, 5, 1, 1)
        self.tsi60_GBPNZD = QtWidgets.QLabel(Dialog)
        self.tsi60_GBPNZD.setObjectName("tsi60_GBPNZD")
        self.gridLayout_4.addWidget(self.tsi60_GBPNZD, 20, 5, 1, 1)
        self.tsi60_GBPUSD = QtWidgets.QLabel(Dialog)
        self.tsi60_GBPUSD.setObjectName("tsi60_GBPUSD")
        self.gridLayout_4.addWidget(self.tsi60_GBPUSD, 21, 5, 1, 1)
        self.tsi60_NZDCAD = QtWidgets.QLabel(Dialog)
        self.tsi60_NZDCAD.setObjectName("tsi60_NZDCAD")
        self.gridLayout_4.addWidget(self.tsi60_NZDCAD, 22, 5, 1, 1)
        self.tsi60_NZDCHF = QtWidgets.QLabel(Dialog)
        self.tsi60_NZDCHF.setObjectName("tsi60_NZDCHF")
        self.gridLayout_4.addWidget(self.tsi60_NZDCHF, 23, 5, 1, 1)
        self.tsi60_NZDJPY = QtWidgets.QLabel(Dialog)
        self.tsi60_NZDJPY.setObjectName("tsi60_NZDJPY")
        self.gridLayout_4.addWidget(self.tsi60_NZDJPY, 24, 5, 1, 1)
        self.tsi60_NZDUSD = QtWidgets.QLabel(Dialog)
        self.tsi60_NZDUSD.setObjectName("tsi60_NZDUSD")
        self.gridLayout_4.addWidget(self.tsi60_NZDUSD, 25, 5, 1, 1)
        self.tsi60_USDCAD = QtWidgets.QLabel(Dialog)
        self.tsi60_USDCAD.setObjectName("tsi60_USDCAD")
        self.gridLayout_4.addWidget(self.tsi60_USDCAD, 26, 5, 1, 1)
        self.tsi60_USDCHF = QtWidgets.QLabel(Dialog)
        self.tsi60_USDCHF.setObjectName("tsi60_USDCHF")
        self.gridLayout_4.addWidget(self.tsi60_USDCHF, 27, 5, 1, 1)
        self.tsi60_USDJPY = QtWidgets.QLabel(Dialog)
        self.tsi60_USDJPY.setObjectName("tsi60_USDJPY")
        self.gridLayout_4.addWidget(self.tsi60_USDJPY, 28, 5, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LABEL_AUDCAD.setText(_translate("Dialog", "AUDCAD"))
        self.LABEL_AUDUSD.setText(_translate("Dialog", "AUDUSD"))
        self.LABEL_EURNZD.setText(_translate("Dialog", "EURNZD"))
        self.LABEL_GBPJPY.setText(_translate("Dialog", "GBPJPY"))
        self.LABEL_GBPNZD.setText(_translate("Dialog", "GBPNZD"))
        self.LABEL_CADJPY.setText(_translate("Dialog", "CADJPY"))
        self.LABEL_EURCHF.setText(_translate("Dialog", "EURCHF"))
        self.LABEL_AUDJPY.setText(_translate("Dialog", "AUDJPY"))
        self.LABEL_EURCAD.setText(_translate("Dialog", "EURCAD"))
        self.LABEL_AUDNZD.setText(_translate("Dialog", "AUDNZD"))
        self.LABEL_GBPCHF.setText(_translate("Dialog", "GBPCHF"))
        self.LABEL_CHFJPY.setText(_translate("Dialog", "CHFJPY"))
        self.LABEL_CADCHF.setText(_translate("Dialog", "CADCHF"))
        self.LABEL_EURJPY.setText(_translate("Dialog", "EURJPY"))
        self.LABEL_EURAUD.setText(_translate("Dialog", "EURAUD"))
        self.LABEL_NZDCAD.setText(_translate("Dialog", "NZDCAD"))
        self.LABEL_GBPUSD.setText(_translate("Dialog", "GBPUSD"))
        self.LABEL_NZDCHF.setText(_translate("Dialog", "NZDCHF"))
        self.LABEL_EURUSD.setText(_translate("Dialog", "EURUSD"))
        self.LABEL_NZDJPY.setText(_translate("Dialog", "NZDJPY"))
        self.LABEL_AUDCHF.setText(_translate("Dialog", "AUDCHF"))
        self.LABEL_EURGBP.setText(_translate("Dialog", "EURGBP"))
        self.LABEL_GBPAUD.setText(_translate("Dialog", "GBPAUD"))
        self.LABEL_GBPCAD.setText(_translate("Dialog", "GBPCAD"))
        self.LABEL_NZDUSD.setText(_translate("Dialog", "NZDUSD"))
        self.LABEL_USDCAD.setText(_translate("Dialog", "USDCAD"))
        self.LABEL_USDCHF.setText(_translate("Dialog", "USDCHF"))
        self.LABEL_USDJPY.setText(_translate("Dialog", "USDJPY"))
        self.range20min5title.setText(_translate("Dialog", "Range20(5min)"))
        self.range20min5_AUDCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_AUDCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_AUDJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_AUDNZD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_AUDUSD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_CADCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_CADJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_CHFJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_EURAUD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_EURCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_EURCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_EURGBP.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_EURJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_EURNZD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_EURUSD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_GBPAUD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_GBPCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_GBPCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_GBPJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_GBPNZD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_GBPUSD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_NZDCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_NZDCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_NZDJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_NZDUSD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_USDCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_USDCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min5_USDJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min15title.setText(_translate("Dialog", "Range20(15min)"))
        self.range20min15_AUDCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_AUDCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_AUDJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_AUDNZD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_AUDUSD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_CADCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_CADJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_CHFJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_EURAUD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_EURCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_EURCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_EURGBP.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_EURJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_EURNZD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_EURUSD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_GBPAUD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_GBPCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_GBPCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_GBPJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_GBPNZD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_GBPUSD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_NZDCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_NZDCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_NZDJPY.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_NZDUSD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_USDCAD.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_USDCHF.setText(_translate("Dialog", "TextLabel"))
        self.range20min15_USDJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi5title.setText(_translate("Dialog", "TSI(5min)"))
        self.tsi5_AUDCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_AUDCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_AUDJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_AUDNZD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_AUDUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_CADCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_CADJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_CHFJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_EURAUD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_EURCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_EURCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_EURGBP.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_EURJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_EURNZD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_EURUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_GBPAUD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_GBPCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_GBPCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_GBPJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_GBPNZD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_GBPUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_NZDCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_NZDCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_NZDJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_NZDUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_USDCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_USDCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi5_USDJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi15title.setText(_translate("Dialog", "TSI(15min)"))
        self.tsi15_AUDCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_AUDCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_AUDJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_AUDNZD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_AUDUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_CADCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_CADJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_CHFJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_EURAUD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_EURCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_EURCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_EURGBP.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_EURJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_EURNZD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_EURUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_GBPAUD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_GBPCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_GBPCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_GBPJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_GBPNZD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_GBPUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_NZDCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_NZDCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_NZDJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_NZDUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_USDCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_USDCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi15_USDJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi60title.setText(_translate("Dialog", "TSI(60min)"))
        self.tsi60_AUDCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_AUDCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_AUDJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_AUDNZD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_AUDUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_CADCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_CADJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_CHFJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_EURAUD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_EURCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_EURCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_EURGBP.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_EURJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_EURNZD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_EURUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_GBPAUD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_GBPCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_GBPCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_GBPJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_GBPNZD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_GBPUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_NZDCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_NZDCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_NZDJPY.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_NZDUSD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_USDCAD.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_USDCHF.setText(_translate("Dialog", "TextLabel"))
        self.tsi60_USDJPY.setText(_translate("Dialog", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

